from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('api/properties', views.properties, name='properties'),
    path('api/properties/<pk>', views.property_details, name='property_details'),
    path('api/tenants', views.tenants, name='tenants'),
    path('api/tenants/<pk>', views.tenant_details, name='tenant_details'),
    path('api/units', views.units, name='units'),
    path('api/units/<pk>', views.unit_details, name='unit_details'),
    path('api/leases', views.leases, name='leases'),
    path('api/leases/<pk>', views.lease_details, name='lease_details'),
    path("", views.index, name='index'),
    path("properties", views.property_list, name='property_list'),
    path("logins", views.user_login, name='user_login'),
    path("logout", views.user_logout, name='user_logout'),
    path("register", views.register, name='register'),
    path("about",views.about,name='about'),
    path('admin_dashboad', views.admin_dashboard, name='admin_dashboard'),
    path('user_register', views.user_register, name='user_register'),
    path('contact', views.contact, name='contact'),
    path("updates", views.updates, name='updates'),
    path('property_lists', views.property_lists, name='property_lists'),
    path('admin_dashboard/properties',views.admin_properties,name='admin_properties'),
    path('tenant_lists', views.tenant_list, name='tenant_list'),
    path('owner_list', views.owner_list, name='owner_list'),
    path('totals', views.totals, name='totals'),
    path('edit_property/<id>', views.edit_property, name='edit_property'),
    path('admin_dashboard/delete_property/<id>', views.delete_property, name='delete_property'),
    path('properties/<id>', views.property_view, name='property_view'),
    path('adding_property', views.adding_property, name='adding_property'),
    path('admin_dashboard/add_property',views.add_property,name='add_property'),
    path('editing_property/<id>', views.editing_property, name='editing_property'),
    path('admin_dashboard/users',views.admin_users,name='admin_users'),
    path('adding_user', views.adding_user, name='adding_user'),
    path('admin_dashboard/users/add_user',views.add_user,name='add_user'),
    path('editing_user/<id>', views.editing_user, name='editing_user'),
    path('admin_dashboard/edit_user/<id>', views.edit_user, name='edit_user'),
    path('admin_dashboard/delete_user/<id>', views.delete_user, name='delete_user'),
    path('admin_dashboard/users/disapprove_user/<id>', views.disapprove_user, name='disapprove_user'),
    path('admin_dashboard/users/approve_user/<id>', views.approve_user, name='approve_user'),
    path('admin_dashboard/owners',views.admin_owners,name='admin_owners'),
    path('adding_owner', views.adding_owner, name='adding_owner'),
    path('editing_owner/<id>', views.editing_owner, name='editing_owner'),
    path('admin_dashboard/add_owner',views.add_owner,name='add_owner'),
    path('admin_dashboard/edit_owner/<id>', views.edit_owner, name='edit_owner'),
    path('admin_dashboard/delete_owner/<id>', views.delete_owner, name='delete_owner'),
    path('admin_dashboard/updates',views.admin_updates,name='admin_updates'),
    path('adding_update',views.adding_update,name='adding_update'),
    path('admin_dashboard/add_update',views.add_update,name='add_update'),
    path('admin_dashboard/edit_update/<id>', views.edit_update, name='edit_update'),
    path('editing_update/<id>', views.editing_update, name='editing_update'),
    path('admin_dashboard/delete_update/<id>', views.delete_update, name='delete_update'),
    path('admin_messages', views.message_list_view, name='message_list'),
    path('mark-as-read/<int:message_id>/', views.mark_as_read_view, name='mark_as_read'),
    path('delete-message/<int:message_id>/', views.delete_message_view, name='delete_message'),
    path('archive-message/<int:message_id>/', views.archive_message_view, name='archive_message'),
    path('customer_message', views.customer_message, name='customer_message'),
    path('mail/<int:message_id>/', views.mail, name='mail'),
    path('send_email', views.send_email, name='send_email'),
    path('read-message/<int:message_id>/', views.read_message, name='read_message'),
    path('admin_dashboard/tenants',views.admin_tenants,name='admin_tenants'),
    path('delete_tenant/<int:tenant_id>/', views.delete_tenant, name='delete_tenant'),
    path('admin_dashboard/leases', views.manage_leases, name='manage_leases'),
    path('admin_dashboard/leases/add/', views.add_lease, name='add_lease'),
    path('admin_dashboard/leases/edit/<int:lease_id>/', views.edit_lease, name='edit_lease'),
    path('owner/contracts/<int:user_id>/edit/<int:lease_id>/', views.owner_edit_contract, name='owner_edit_contract'),
    path('lease-details/<int:lease_id>/', views.lease_details, name='lease_details'),
    path('sign-lease/<int:lease_id>/', views.sign_lease, name='sign_lease'),
    path('delete-lease/<int:lease_id>/', views.delete_lease, name='delete_lease'),
    path('archive-lease/<int:lease_id>/', views.archive_lease, name='archive_lease'),
    path('admin-inquiries', views.admin_inquiries, name='admin_inquiries'),
    path('admin_enquiries/view_enquiry/<int:pk>/', views.viewEnquiry, name='view_enquiry'),
    path('admin_enquiries/mark-as-read/<int:pk>/', views.mark_as_read_enquiry, name='mark_as_read_enquiry'),
    path('admin_enquiries/archive-message/<int:pk>/', views.archive_enquiry, name='archive_enquiry'),
    path('admin_enquiries/delete-message/<int:pk>/', views.delete_enquiry, name='delete_enquiry'),
    path('customer_enquiry/<int:id>', views.customer_enquiry, name='customer_enquiry'),
    path('admin_enquiries/unarchive_message/<int:pk>/', views.unarchive_enquiry, name='unarchive_enquiry'),
    path('admin_enquiries/send_email', views.send_enquiry_email, name='send_enquiry_email'),
    path('admin_enquiries/reply_enquiry/<int:id>/', views.mail_enquiry, name='mail_enquiry'),
    path('admin_users/users/make_owner/<int:user_id>/', views.make_owner, name='make_owner'),
    path('admin_users/users/make_admin/<int:user_id>/', views.make_admin, name='make_admin'),
    path('admin_users/users/remove_owner/<int:user_id>/', views.unmake_owner, name='unmake_owner'),
    path('admin_users/users/remove_admin/<int:user_id>/', views.unmake_admin, name='unmake_admin'),
    path('admin_users/users/make_agent/<int:user_id>/', views.make_agent, name='make_agent'),
    path('admin_users/users/make_seller/<int:user_id>/', views.make_seller, name='make_seller'),
    path('admin_users/users/remove_agent/<int:user_id>/', views.unmake_agent, name='unmake_agent'),
    path('admin_users/users/remove_seller/<int:user_id>/', views.unmake_seller, name='unmake_seller'),
    path('owner_dashboard/<int:user_id>/', views.owner_dashboard, name='owner_dashboard'),
    path('owner_profile/<int:user_id>/', views.owner_profile, name='owner_profile'),
    path('owner_profile/edit_profile/<int:id>/', views.edit_owner_profile, name='edit_owner_profile'),
    path('view_profile/<int:user_id>/', views.view_profile, name='view_profile'),
    path('create_owner_profile/<int:user_id>/', views.create_owner_profile, name='create_owner_profile'),
    path('owner/properties/<int:user_id>/', views.owner_properties, name='owner_properties'),
    path('owner_properties/add_property/<int:user_id>', views.owner_add_property, name='owner_add_property'),
    path('owner_contracts/<int:user_id>/', views.owner_contracts, name='owner_contracts'),
    path('owner_contracts/add_contract/<int:user_id>', views.new_contract, name='new_contract'),
    path('owner_view_contract/<int:lease_id>/', views.owner_view_contract, name='owner_view_contract'),
    path('download_contract/<int:lease_id>/',views.download_contract,name='download_contract'),
    path('delete_contract/<int:lease_id>/',views.delete_contract,name='delete_contract'),
    path('owner_properties/edit_property/<int:property_id>', views.owner_edit_property, name='owner_edit_property'),
    path('owner_properties/delete_property/<int:property_id>', views.owner_delete_property, name='owner_delete_property'),
    path('owner_properties/view_property/<int:property_id>', views.owner_view_property, name='owner_view_property'),
    path('tenant_dashboard/<int:user_id>/', views.tenant_dashboard, name='tenant_dashboard'),
    path('new_tenant/<int:user_id>/', views.new_tenant, name='new_tenant'),
    path('property/<int:property_id>/like/', views.like_property, name='like_property'),
    path('property/<int:property_id>/schedule/', views.schedule_visit, name='schedule_visit'),
    path('Tenant_profile/<int:user_id>/', views.tenant_profile, name='tenant_profile'),
    path('tenant_profile/edit_profile/<int:user_id>/', views.tenant_edit_profile, name='tenant_edit_profile'),
    path('tenant_properties/<int:user_id>',views.tenant_properties, name='tenant_properties'),
    path('tenant_contracts/<int:user_id>/', views.tenant_contracts, name='tenant_contracts'),
    path('tenant_view_contract/<int:lease_id>/', views.tenant_view_contract, name='tenant_view_contract'),
    path('tenant_sign_contract/<int:lease_id>/', views.tenant_sign_contract, name='tenant_sign_contract'),
    path('tenant_accepet_contract/<int:lease_id>/', views.tenant_accept_contract, name='tenant_accept_contract'),
    path('tenant_download_contract/<int:lease_id>/',views.tenant_download_contract,name='tenant_download_contract'),
    path('tenant_view_property/<int:property_id>', views.tenant_view_property, name='tenant_view_property'),
    path('tenant/messages/<int:user_id>/', views.tenant_messages, name='tenant_messages'),
    path('tenant/messages/<int:user_id>/conversation/<int:contact_id>/', views.tenant_conversation, name='tenant_conversation'),
    path('tenant/messages/<int:user_id>/delete/<int:message_id>/', views.tenant_delete_message, name='tenant_delete_message'),
    path('admin_dashboard/tenant-messages/', views.admin_tenant_inbox, name='admin_tenant_inbox'),
    path('admin_dashboard/tenant-messages/conversation/<int:contact_id>/', views.admin_conversation, name='admin_conversation'),
    path('admin_dashboard/tenant-messages/delete/<int:message_id>/', views.admin_delete_message, name='admin_delete_message'),
   path('tenant/make_payment/', views.process_payment, name='make_payment'),
    path('payment/execute/', views.execute_payment, name='execute_payment'),
    path('tenant/maintenance/<int:user_id>/', views.tenant_maintenance, name='tenant_maintenance'),
    path('tenant/maintenance/new/<int:user_id>/', views.new_maintenance_request, name='new_maintenance_request'),
    # Owner messaging
    path('owner/messages/<int:user_id>/', views.owner_messages, name='owner_messages'),
    path('owner/messages/<int:user_id>/conversation/<int:contact_id>/', views.owner_conversation, name='owner_conversation'),
    path('owner/messages/<int:user_id>/delete/<int:message_id>/', views.owner_delete_message, name='owner_delete_message'),
    # Admin maintenance management
    path('admin_dashboard/maintenance/', views.admin_maintenance, name='admin_maintenance'),
    path('admin_dashboard/maintenance/update/<int:request_id>/', views.admin_update_maintenance, name='admin_update_maintenance'),
    # Owner maintenance management
    path('owner/maintenance/<int:user_id>/', views.owner_maintenance, name='owner_maintenance'),
    path('owner/maintenance/<int:user_id>/update/<int:request_id>/', views.owner_update_maintenance, name='owner_update_maintenance'),

    # ═══════════════════════════════════════════════════════════
    #   REAL ESTATE MARKETPLACE URLS
    # ═══════════════════════════════════════════════════════════

    # Public: Sale listings & agents
    path('for-sale/', views.sale_listings, name='sale_listings'),
    path('for-sale/<int:pk>/', views.sale_property_detail, name='sale_property_detail'),
    path('agents/', views.agent_directory, name='agent_directory'),
    path('agents/<int:pk>/', views.agent_profile_public, name='agent_profile_public'),

    # Seller dashboard
    path('create_seller_profile/<int:user_id>/', views.create_seller_profile, name='create_seller_profile'),
    path('seller_dashboard/<int:user_id>/', views.seller_dashboard, name='seller_dashboard'),
    path('seller/add-property/<int:user_id>/', views.seller_add_property, name='seller_add_property'),
    path('seller/edit-property/<int:user_id>/<int:property_id>/', views.seller_edit_property, name='seller_edit_property'),
    path('seller/delete-property/<int:user_id>/<int:property_id>/', views.seller_delete_property, name='seller_delete_property'),
    path('seller/offers/<int:user_id>/', views.seller_offers, name='seller_offers'),
    path('seller/offers/<int:user_id>/respond/<int:offer_id>/', views.seller_respond_offer, name='seller_respond_offer'),
    path('seller/inquiries/<int:user_id>/', views.seller_inquiries, name='seller_inquiries'),

    # Agent dashboard
    path('create_agent_profile/<int:user_id>/', views.create_agent_profile, name='create_agent_profile'),
    path('agent_dashboard/<int:user_id>/', views.agent_dashboard, name='agent_dashboard'),
    path('agent/properties/<int:user_id>/', views.agent_assigned_properties, name='agent_assigned_properties'),
    path('agent/schedule-visit/<int:user_id>/<int:property_id>/', views.agent_schedule_visit, name='agent_schedule_visit'),
    path('agent/visits/<int:user_id>/', views.agent_site_visits, name='agent_site_visits'),
    path('agent/visits/<int:user_id>/update/<int:visit_id>/', views.agent_update_visit, name='agent_update_visit'),
    path('agent/offers/<int:user_id>/', views.agent_offers, name='agent_offers'),
    path('agent/upload-photos/<int:user_id>/<int:property_id>/', views.agent_upload_photos, name='agent_upload_photos'),

    # Admin marketplace management
    path('admin_dashboard/sale-properties/', views.admin_sale_properties, name='admin_sale_properties'),
    path('admin_dashboard/assign-agent/<int:property_id>/', views.admin_assign_agent, name='admin_assign_agent'),
    path('admin_dashboard/agents/', views.admin_agents, name='admin_agents'),
    path('admin_dashboard/verify-agent/<int:agent_id>/', views.admin_verify_agent, name='admin_verify_agent'),
    path('admin_dashboard/sellers/', views.admin_sellers, name='admin_sellers'),
    path('admin_dashboard/verify-seller/<int:seller_id>/', views.admin_verify_seller, name='admin_verify_seller'),
    path('admin_dashboard/all-offers/', views.admin_all_offers, name='admin_all_offers'),

    # ── Social Feed ──────────────────────────────────────────────
    path('feed/', views.feed_view, name='feed'),
    path('feed/create/', views.create_post_view, name='create_post'),
    path('feed/post/<int:post_id>/', views.post_detail_view, name='post_detail'),
    path('feed/post/<int:post_id>/like/', views.like_post_view, name='like_post'),
    path('feed/post/<int:post_id>/repost/', views.repost_view, name='repost'),
    path('feed/post/<int:post_id>/comment/', views.add_comment_view, name='add_comment'),
    path('feed/post/<int:post_id>/delete/', views.delete_post_view, name='delete_post'),
    path('feed/tag/<str:tag>/', views.hashtag_feed_view, name='hashtag_feed'),

    # ── Notifications ────────────────────────────────────────────
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/<int:notif_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/read-all/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
]





